import {catchAsyncError} from "../middlewares/catchAsyncError.js";
import ErrorHandler from "../utils/ErrorHandler.js";
import User from "../models/User.js"


export const register = catchAsyncError(async(req,res,next) =>{

})

export const login = catchAsyncError(async(req,res,next)=>{

})


export const logout = catchAsyncError(async(req,res,next)=>{
    
})
